# Generated by Django 3.2.16 on 2022-12-15 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20221215_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='shop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shop'),
        ),
    ]
